### ISSUE TITLE
How to include twig.js with Backbone.js

### ISSUE THREAD

**Issue by dupuchba** [schmittjoh/JMSTwigJsBundle#10]
Hello everyone,

Does anyone know how to include twig.js with Backbone.js to leverage symfony and backbone without having to handle many template files!!!

Thx and nice work @schmittjoh.

**Comment by schmittjoh** [comment]
Can you elaborate this?

**Comment by dupuchba** [comment]
Ok, I am going to have a deeper look, but I am not sure to be fully qualified :). I will post my ideas though!

**Comment by dupuchba** [comment]
So, I had a look on that point ... and it took a while for me to understand as I am quite busy at work.

The good news is, Backbone.js integrates pretty good with symfony. 
It's quite easy to implement javascript logic on client side.

So symfony+backbone+REST applications is quite powerful.

Backbone use underscore.js (it's only dependency) to manage template http://documentcloud.github.com/underscore/#template which can apparently manage different template engine.
Unfornunatly, I have not add the time to see how can we include twig.js. 
I am still working on it...

**Comment by coduar** [comment]
@dupuchba Please write something when you will manage to use twig.js as a backbone templating engine. I'm strongly interested in this.
