### ISSUE TITLE
HashableInterface doesn't exist out of the box

### ISSUE THREAD

**Issue by adam-lynch** [schmittjoh/JMSTwigJsBundle#14]
What I did: 
- Downloaded Symfony 2.0.16 with vendors
- Installed JMSTwigJsBundle
- Set up basic example (not even rendering, just using assetic "twig_js" filter to compile the template to JS and load in script tag)

What I got: Fatal error: Interface 'Assetic\Filter\HashableInterface' not found in D:\Tools\Apache2.2\htdocs\Symfony\vendor\twig.js\src\TwigJs\Assetic\TwigJsFilter.php on line 28

I had to add it myself (from http://apigen.juzna.cz/doc/kriswallsmith/assetic/source-class-Assetic.Filter.HashableInterface.html).

Related: https://github.com/schmittjoh/twig.js/pull/29

**Comment by schmittjoh** [comment]
Please upgrade your assetic version to 1.1.
