### ISSUE TITLE
Documentation should declare that setting runtime filters are impossible (with Assetic), or else contain solid example

### ISSUE THREAD

**Issue by adam-lynch** [schmittjoh/JMSTwigJsBundle#18]
That's basically it. I could not get Assetic to play nice with a filter I wanted to add/set at runtime. I understand if it's impossible, because Assetic would have to parse all JS and parse all "Twig.set..." calls. 

I tried the following:
- Loading Twig-JS and the filter definition file in the head
- Hardcoding the filter definition in the head after TwigJS is parsed by Assetic
- Hardcoding the filter definition into twig.js and twig.dev.js
- Looked into the PHP and JS unit tests for clues
- Manually adding a function to twig.filter at runtime
- Reduced the complexity of the template (include/extend was used) I was testing on, made sure there was no calls to the filter before it was defined/set.
- Setting the filter using Assetic to parse the file (containing the TwigJS filter defintion) using the twig_js filter
- Adding a macro in a Twig template and using it directly afterwards
- Adding a runtime function

**Comment by schmittjoh** [comment]
Could you maybe sum-up what you were trying to do?

**Comment by adam-lynch** [comment]
Ideally I'd like to create my own date filter. I'd set it at runtime because I'd like to avoid using a fork of the project in my application, or editing files after every time I install from composer. 

**But** to start, I tried to just add a simple filter which concatenates the value with something. 

If possible, how exactly can you set a runtime filter using the Symfony bundle and Assetic?

**Comment by schmittjoh** [comment]
Hm, I'm not sure we have the same definition of "runtime" filter.

Maybe you could make a high-level description of what you would like to do.
How does your template look like, and what is the expected html that you'd
like twig.js to generate?

**Comment by adam-lynch** [comment]
Ah ok I see. 

We need to be able to format dates in our templates (client side and server side rendering). Ideally we'd like to write a TwigJS date filter, which contains just enough functionality (of the Twig date filter) for our formatting use case(s). 

When you say compile vs runtime, do you mean pre and post Google Closure compilation? I'm not sure. I assumed you meant we could add filters somehow in JS which Assetic used when pre-processing (somehow). 

What's the easiest way to add a custom filter? By "easiest" I mean with the minimal amount of changes to the TwigJS/JMSTwigJMSBundle source/project.

**Comment by schmittjoh** [comment]
The easiest way is to add a function:

``` js
Twig.addFilter('date', function() { }); 
```

This needs to be after you include the twig.js file, and before you call Twig.render.

**Comment by adam-lynch** [comment]
Thanks.
I'm assuming you meant to say `Twig.setFilter()`.

It now seems to be setting the filter but it's not behaving as expected.

**The filter definition:**

``` javascript
Twig.setFilter('date', function(value){
     console.debug(value); 
     return 'foo' + value + 'bar'; 
});
```

**The call in the template:**

``` html
<h1>{{ 'hello'|date }}</h1>
```

**The resultant HTML:**

``` html
<h1>foo[object Object]bar</h1>
```

I've also tried `<h1>{{ 'hello'|date('a') }}</h1>` but I get the same result.

I'd expect the console to show that value contains the string 'hello' but it actually contains an object something like the following:

``` javascript
b
    b: Object
    f: Object
    g: Object
    h: Object
    l: Object
    o: Object
    p: true
    __proto__: b
```

**Comment by schmittjoh** [comment]
You get the same args that the PHP filter requested.

The first argument is likely the environment (Twig), the value could be one
of the following arguments, check console.log(arguments).

**Comment by adam-lynch** [comment]
Oh yeah I forgot about the environment. Thanks very much!

**Comment by schmittjoh** [comment]
Great that it works now!

Theoretically, it should be really easy to add a filter. It would be cool
to know why you seemed to have trouble with it even though you seem to have
tried a couple of things.

This would help to improve this for others. Where did you start? Which docs
have you followed?

**Comment by adam-lynch** [comment]
Good idea but I'm not really sure. I followed the typical stuff, documentation I linked earlier, etc. I must have skimmed over it and made a basic mistake early on. Then assuming it was a much bigger problem than it is was, started digging into TwigJS, etc.
