### ISSUE TITLE
Q: Twig_Error_Runtime when dumping assets

### ISSUE THREAD

**Issue by minixxie** [schmittjoh/JMSTwigJsBundle#2]
Hi all,

When I'm following the doc:
1) add a name in my twig template file: {% twig_js name="Kuulabu_kuulabuListItemTemplate" %}
2) add this:
        {% javascripts "@KuulabuKuulabuBundle/Resources/views/Kuulabu/kuulabuListItemTemplate.html.twig"
            filter="twig_js" %}
            <script type="text/javascript" language="javascript" src="{{ asset_url }}"></script>
        {% endjavascripts %}

3) when I issue the dump asset command:  php app/console assetic:dump --env=prod --no-debug, I got:

  [Twig_Error_Runtime]  
  Attribute "safe" does not exist for Node "Twig_Node_Set" in "Resources\/views\/Kuulabu\/kuulabuListItemTemplate.html.twig".  

assetic:dump [--watch] [--force] [--period="..."] [write_to]

Any ideas? Many Thanks.

Simon

**Comment by schmittjoh** [comment]
Do you use Twig 1.4?

**Comment by minixxie** [comment]
Sorry, I'm not sure if I'm correct, am I using v1.1.2? this is the deps file:
[twig]
    git=http://github.com/fabpot/Twig.git
    version=v1.1.2

And this is the deps.lock file:
twig 396435ecd05556adb0a8bd05b14641cb4f8a8aa5

So do you mean the minimum req for Twig is >=1.4?

**Comment by schmittjoh** [comment]
twig.js is only tested with Twig 1.4, older versions might work partially
but untested.

On Wed, Dec 14, 2011 at 10:49 AM, minixxie <
reply@reply.github.com

**Comment by minixxie** [comment]
Hi Johannes,

Thank you very much. Let me try 1.4. Thanks again.

Simon
