### ISSUE TITLE
Install failing with composer

### ISSUE THREAD

**Issue by webkod3r** [schmittjoh/JMSTwigJsBundle#35]
Hi everyone, I need some help to install this bundles in order to render my templates in javascript.

When I trying to install the bundle with this: <code>"jms/twig-js-bundle": "dev-master"</code> in my composer.json, I recieve the following error:

<pre><code>
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for jms/twig-js-bundle dev-master -> satisfiable by jms/twig-js-bundle[dev-master].
- jms/twig-js-bundle dev-master requires jms/twig-js dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
see for more details.

Read for further common problems.
</code></pre>

Thanks for any help
WK.

**Comment by kimlai** [comment]
I think that's because `jms/twig-js-bundle` has a dependency on the unstable package `jms/twig-js`. Requiring it explicitely should do the trick : 

``` json
{
    ...
    "require": {
        "jms/twig-js-bundle": "dev-master",                                                                                                                               
        "jms/twig-js": "@dev"
    }
    ...
}
```

**Comment by webkod3r** [comment]
Thanks @kimlai, your solution solve my problem ;)
