### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by shouze** [schmittjoh/JMSTwigJsBundle#37]
As twigjs is now tagged, what about upgrading composer.js [as suggested](https://github.com/schmittjoh/twig.js/issues/84#issuecomment-52626109) by @Gadgetdude would be helpful to tag use the tagged version right now in the bundle... and maybe to also tag the bundle? :)
`"jms/twig-js": "~1.0.0"`

**Comment by shouze** [comment]
Linked to https://github.com/schmittjoh/JMSTwigJsBundle/pull/38

**Comment by armandabric** [comment]
:+1:

**Comment by RolfBabijn** [comment]
Thanks for reporting, I hope @schmittjoh (or another project owner) will implement this slight change soon. :+1:

**Comment by schmittjoh** [comment]
Done.
