### ISSUE TITLE
Can we port functions like form_errors, form_row, form_widget?

### ISSUE THREAD

**Issue by jonathaningram** [schmittjoh/JMSTwigJsBundle#5]
Originally created at https://github.com/schmittjoh/twig.js/issues/18:

Is it easy and possible for me to provide a PR to enable use of the `Symfony\Bridge\Twig\Extension\FormExtension` functions:

``` php
<?php
'form_enctype'             => new \Twig_Function_Method($this, 'renderEnctype', array('is_safe' => array('html'))),
'form_widget'              => new \Twig_Function_Method($this, 'renderWidget', array('is_safe' => array('html'))),
'form_errors'              => new \Twig_Function_Method($this, 'renderErrors', array('is_safe' => array('html'))),
'form_label'               => new \Twig_Function_Method($this, 'renderLabel', array('is_safe' => array('html'))),
'form_row'                 => new \Twig_Function_Method($this, 'renderRow', array('is_safe' => array('html'))),
'form_rest'                => new \Twig_Function_Method($this, 'renderRest', array('is_safe' => array('html'))),
'csrf_token'               => new \Twig_Function_Method($this, 'getCsrfToken'),
'_form_is_choice_group'    => new \Twig_Function_Method($this, 'isChoiceGroup', array('is_safe' => array('html'))),
'_form_is_choice_selected' => new \Twig_Function_Method($this, 'isChoiceSelected', array('is_safe' => array('html'))),
```

In twig.js? I could be on the wrong workflow with what I am doing, but basically I have overridden some blocks for my forms (this is for a collection type, so think of many rows in the form that you can add and remove), and I'd like to be able to render the row in JavaScript in order that I can dynamically add rows using twig.js. My overridden template for my type `mytype` (e.g. `form.html.twig`) is similar to this:

``` jinja
{%- block acme_core_mytype_row -%}
    <tr>
        <td>
            {{- form_errors(form) -}}
            {{- form_row(form.key) -}}
            {{- form_row(form.value) -}}
        </td>
        <td class="tools">
            {{- block('tools') -}}
        </td>
    </tr>
{%- endblock -%}
```

With the intent that I can call this from JS:

``` js
var myTemplate = new acme.core.mytype.form.html(Twig);

$("table.mytable tbody").append(myTemplate.renderBlock("acme_core_mytype_row", {
    form: {
        // all the properties of the form that I want to be in the new row
    }
}));
```

What do you think?

**Comment by jonathaningram** [comment]
@schmittjoh can you give me some first steps to implement this? I've just been looking through the code and it does not really look like a small task to implement this!

As a first step, I'm able to get my block to call a function rather than use invoke by doing this in a compiler pass:

``` php
<?php

// The idea here being that for all registered functions in the twig environment (or maybe registered functions in an extension), we add a method call
$compiler->addMethodCall('setJsFunction', array(
    // this is <method_name>
    'form_errors',
    // this is <extension_name>.<method_name>
    'form.form_errors',
));
```

Which gives me a line like this in my block:

``` js
// line 23
sb.append(form.form_errors("form" in context ? context["form"] : null));
```

The next step is then to have the JS function `form.form_errors` available....

Anyway, I appreciate any pointers you have as I'd really like to contribute to this library, especially because you do not have much time.

**Comment by schmittjoh** [comment]
Ok, what I'd suggest is to basically create a second .js file, i.e. "twig.form.js", which can be loaded in addition to the "twig.js" file should people need the forms functionality.

That file will then host all your form related functions. Currently, as you may have seen, I haven't implemented the notion of an "Extension" in the Javascript version because most of the work is shifted to compile-time rather than runtime and it didn't seem necessary. So, you might need to create a singleton instance of your form related functions like this for example:

``` js
// twig.form.js
/**
 * @constructor
 */
twig.FormExtension = function() {
};

/**
 * ...
 */
twig.FormExtension.prototype.errors = function(/** ... */) {
};

window['twig.form'] = new twig.FormExtension();
```

You can then tell the compiler to map the twig function "form_errors" to the Javascript function "twig.form.errors", and also include the "twig.form.js" on your site, for example like this:

``` html+jinja
{% javascripts "%kernel.root_dir%/../twig.js/twig.js" "@JMSTwigJsBundle/Resources/public/twig.form.js" filter="?yui_js" %}
{# ... #}
{% endjavascripts %}
```

**Comment by jonathaningram** [comment]
OK I think it would be good to get my FormExtension up into a PR for a) any feedback and b) to ensure that the code is not duplicated by others. Currently, I am just developing in a twig.js branch but obviously FormExtension is not specific to twig.js
1. Should I perhaps create a new repo for my FormExtension JS? I.e. each project/bundle/bridge that provides Twig Extensions should also provide another similarly named repo for their Twig.js files? E.g. for SymfonyTwigBridge (which provides Form, Translation, Routing and Yaml extensions) it should also provide a separate SymfonyTwigBridgeTwigJs?
2. Or perhaps we go bigger and map directly to the symfony core? This is what I mean: create a "SymfonyTwigJs" repo that contains everything required from https://github.com/symfony/symfony (including FormView, FormExtension, etc.) For compatibility all files map to the same namespace:

E.g.

In PHP `Symfony\Bridge\Twig\Extension\FormExtension` maps in JS to `symfony.bridge.twig.extension.FormExtension` (in the namespacing and directory tree).

In PHP `Symfony\Component\Form\FormView` maps in JS to `symfony.component.form.FormView`

and (wait for it)

In PHP `Symfony\Component\DependencyInjection\Container` maps in JS to `symfony.component.dependencyInjection.Container` ;)

Some people will probably cringe at the idea of this because:
1. The exact namespacing mapping results in larger JS files than what would be actually necessary.
2. It might seem overkill for just a few files mapped to JS.

So let me know your thoughts on how you think best to proceed. I can imagine many things in the future for twig.js and "symfony.js" so I am trying to avoid just shoving some twig.form.js files into the bundle, but perhaps you might think that's the best first step.

On a side note, I use the FOSRoutingBundle, where you can put in JavaScript `Routing.generate(''my_route", {})`. It's really cool and I actually cannot think of a major problem with it, but imagine with "symfony.js" if we could instead do this:

``` js
var serviceContainer = window["serviceContainer"];

// ...

var router = serviceContainer.get("router");

$.ajax({
    url: router.generate("my_route", {})
});
```

I think that's pretty cool too.

**Comment by schmittjoh** [comment]
Sounds like you want to re-implement Symfony2 in Javascript :)

I'd suggest to first test the code a bit more, and see how it works in practice. If we see that it's good, we can still propose to move it to the symfony/symfony repository. As such I'd keep it in the bundle for now, also to make it easier for people to test it out.

**Comment by jonathaningram** [comment]
Yes well referring to the recent Web Mozart blog article on forms (http://webmozarts.com/2012/03/06/symfony2-form-architecture/), he says:

> Symfony2 features a brand-new Form component that, to my knowledge, supersedes most existing PHP form libraries in functionality and extensibility (**not counting the still lacking, native JavaScript support**).

That's where it's headed :) but it could not be called `symfony.js` just yet ;)

But your argument is good, so I'll start by putting the files in this repo, but I'll keep it in a branch in my fork until at least the minimal ability functionality for rendering form rows, etc. is working.

**Comment by jonathaningram** [comment]
Feel free to look in my new WIP branch: https://github.com/jonathaningram/JMSTwigJsBundle/tree/form, https://github.com/jonathaningram/JMSTwigJsBundle/tree/form/Resources/public/js

It's quite extreme, but I think it will work out well.

**Comment by schmittjoh** [comment]
Can you send a WIP PR, so that I can comment on the code?

On Fri, Mar 9, 2012 at 12:10 AM, Jonathan Ingram <
reply@reply.github.com

**Comment by jonathaningram** [comment]
PR created.
