### ISSUE TITLE
Trans filter is not available in JS and doc does not help

### ISSUE THREAD

**Issue by jonathaningram** [schmittjoh/JMSTwigJsBundle#6]
I am making progress with the FormExtension, however the trans filter does not seem to work out of the box. The generated JS seems to be fine but the "trans" filter never exists in twig.environment.filters_ (obviously)

I assume that I need to write and provide either a compile time or runtime filter myself (or perhaps even a TransExtension.js - I have not delved deep enough yet), but it would be good if the doc mentioned this (if this is indeed the way to go).

**Comment by schmittjoh** [comment]
Translations are inlined, i.e. resolved at compile-time directly.

``` html+jinja
{% javascripts "my_template.html.twig" vars=["locale"] filter="twig_js" %}
{# ... #}
{% endjavascripts %}
```

We could in addition add some runtime support, but I'm not sure if it's a good idea or necessary. Could you elaborate your use-case?

**Comment by jonathaningram** [comment]
Does that mean that each file compiled with twig.js will only ever be available in one locale though?

The current block I am trying to render is from `form_div_layout.html.twig` as follows:

``` jinja
{% block field_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
    <ul>
        {% for error in errors %}
            <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endspaceless %}
{% endblock field_errors %}
```

Which generates JS as follows:

``` js
// line 248
/**
 * @param {!twig.StringBuffer} sb
 * @param {Object.<*>} context
 * @param {Object.<Function>} blocks
 */
form_div_layout.html.prototype.block_field_errors = function(sb, context, blocks) {
    // line 249
    var slSb = sb;
    sb = new twig.StringBuffer;    // line 250
    sb.append("    ");
    if ((twig.filter.length(this.env_, "errors" in context ? context["errors"] : null) > 0)) {
        // line 251
        sb.append("    <ul>\n        ");
        // line 252
        context['_parent'] = context;
        var seq = "errors" in context ? context["errors"] : null;
        twig.forEach(seq, function(v, k) {
            context["_key"] = k;
            context["error"] = v;
            // line 253
            sb.append("            <li>");
            sb.append(twig.filter.escape(this.env_, this.env_.filter("trans", twig.attr("error" in context ? context["error"] : null, "messageTemplate"), twig.attr("error" in context ? context["error"] : null, "messageParameters"), "validators"), "html", null, true));
            sb.append("<\/li>\n        ");
        }, this);
        // line 255
        sb.append("    <\/ul>\n    ");
    }
    slSb.append(twig.spaceless(sb.toString()));
    sb = slSb;
};
```

You can see the call to the trans filter which looks like this:

``` js
sb.append(twig.filter.escape(this.env_, this.env_.filter("trans", twig.attr("error" in context ? context["error"] : null, "messageTemplate"), twig.attr("error" in context ? context["error"] : null, "messageParameters"), "validators"), "html", null, true));
```

**Comment by schmittjoh** [comment]
It means that assetic will compile one file for each locale, and then include the correct one during runtime, e.g. "file.de.js", "file.en.js", etc. The trans filter will be replaced by the actual translation in each of these files. For this to work, you also need to let assetic know which locales you want to support:

``` yml
assetic:
    variables:
        locale: [de, en]
```

For dynamic translations that you linked above, we need a different strategy. We would somehow need to know which translations should be transferred to the client. You likely don't want to send all your translation files to the client.

**Comment by jonathaningram** [comment]
OK well at least there should be a way to get it to work in the end (could be a good addition to the docs). 

Perhaps we don't want to send all the translation files to the client because:
1. We don't want to expose them for privacy/security reasons.
2. Because of performance including a) page load time and b) bandwidth.

If we ignore 1., perhaps some sort of lazy loading of the translation files via AJAX could be used to satisfy 2(a).

Aside, there is also this bundle which I started to use and it works quite well: https://github.com/willdurand/BazingaExposeTranslationBundle

**Comment by schmittjoh** [comment]
Since this bundle already exists, I'd suggest to simply use it for dynamic translations. No need to re-do the work, and it's very easy. Simply add the following code somewhere after loading twig.js:

``` js
Twig.addFilter("trans", function(env, id, params, domain) {
    return ExposeTranslation.get(domain + ":" + id, params);
});
```

**Comment by Lumbendil** [comment]
I've had it occur again, the template is being defined to use the trans filter, and if it fails, it uses the already inlined translation, which is quite weird.

Note: This template was working, I haven't changed it.
