### ISSUE TITLE
Catchable Fatal Error:

### ISSUE THREAD

**Issue by frequenc1** [schmittjoh/JMSTwigJsBundle#8]
Trying to get this working and I'm running into this:

An exception has been thrown during the compilation of a template ("Catchable Fatal Error: Argument 1 passed to JMS\TwigJsBundle\TwigJs\Compiler\TransFilterCompiler::__construct() must be an instance of Symfony\Component\Translation\Translator, instance of Symfony\Component\Translation\IdentityTranslator given, called in 

Any ideas? am I using a wrong branch of symfony2?

**Comment by maria-p** [comment]
You need to enable translator in your config.yml file 

```
framework:
    translator: { fallback: %locale% }
```
